definitions:
  auth.AuthResponse:
    properties:
      first_name:
        maxLength: 30
        minLength: 3
        type: string
      id:
        type: integer
      jwt:
        $ref: '#/definitions/types.JwtTokens'
      last_name:
        maxLength: 40
        minLength: 3
        type: string
      phone:
        maxLength: 11
        minLength: 11
        type: string
      role:
        type: string
    required:
    - first_name
    - last_name
    - phone
    type: object
  auth.LoginCredential:
    properties:
      password:
        maxLength: 20
        minLength: 3
        type: string
      phone:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - password
    - phone
    type: object
  auth.RegisterResponse:
    properties:
      refreshToken:
        type: string
      token:
        type: string
      user_id:
        type: integer
    type: object
  auth.RequiredOtpRegistering:
    properties:
      phone:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - phone
    type: object
  auth.ValidateOtpRegistering:
    properties:
      otp:
        maxLength: 5
        minLength: 5
        type: string
      phone:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - otp
    - phone
    type: object
  category.NewCategory:
    properties:
      name:
        maxLength: 50
        type: string
      parent_id:
        minimum: 0
        type: integer
    required:
    - name
    type: object
  types.JwtTokens:
    properties:
      refreshToken:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: User registration
      parameters:
      - description: Register request
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/auth.LoginCredential'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.AuthResponse'
      summary: Login
      tags:
      - auth
  /auth/register/send-otp:
    post:
      consumes:
      - application/json
      description: User registration
      parameters:
      - description: Register request
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/auth.RequiredOtpRegistering'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Register
      tags:
      - auth
  /auth/register/validate-otp:
    post:
      consumes:
      - application/json
      description: User otp validation
      parameters:
      - description: Register request
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/auth.ValidateOtpRegistering'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
      summary: Register
      tags:
      - auth
  /category/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Get Category By Id
      tags:
      - category
  /category/add:
    post:
      consumes:
      - application/json
      description: Adding new category by admin
      parameters:
      - description: Adding new category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/category.NewCategory'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Add Category
      tags:
      - category
swagger: "2.0"
